### ISSUE TITLE
Script did not work today

### ISSUE THREAD

**Issue by rajdude** [camerahacks/rpilocator-rss-feed#8]
So I have my script running on my always on Windows 10 machine. Have tested a test version of the script that it is actually able to contact the RSS feed and gives 200 return code

Today morning, Digi-Key went in stock. I noticed two things:
1. I did not get a notification on my phone
2. The auto refresh and alert sound on  also did not work. 

I got a twitter alert and then when I hit F5 on rpilocator website, it started showing Digi-Key

**Comment by rajdude** [comment]
trying the pop testing option now :-)
That should work today

**Comment by rajdude** [comment]
Hmmm........I got a notification just now. I wonder which script sent me the notification? :-)
* I have the unmodified script running on my always on machine
* I have another script with the control.pop() running as a test on my workstation here.
I see that one has a 200 on the console output, but it has not exited.

I suspect the script on my workstation sent me the notification via pushover. I will check pushover logs and see if that shows me from where the notification came from. But I guess it will tell me the IP of my home's router.

**Comment by rajdude** [comment]
Nope, Pushover's website does not show me any log for notifications sent to my phone. They do have a log, but that is for security logs. Interestingly, it does show me test notifications I sent to my phone from their website.

**Comment by camerahacks** [comment]
If you would like to document your own troubleshooting, please do that on your own GitHub. So far, you have opened 3 issues but have not been able to show that the script doesn't actually work. You just wrote that one of your script instances does work.

More than happy to review your issues when you can point out an issue with the script.

**Comment by rajdude** [comment]
sorry about that. Closing this one.

**Comment by rajdude** [comment]
Apologies for adding content to a closed issue...but I thought you may want to know these error messages which occurred after I tried to kill the script. 
No response needed :-) I do not understand most of them anyway.

I am done with my Raspberry Pi hunt, 
Thanks a lot for your help!

````

C:\Users\rajdu\Documents\scripts>py rpilocator-rss-pushover.py
200
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\socket.py", line 833, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rajdu\Documents\scripts\rpilocator-rss-pushover.py", line 69, in <module>
    f = feedparser.parse(FEED_URL, agent=USER_AGENT)
  File "C:\Users\rajdu\AppData\Roaming\Python\Python310\site-packages\feedparser\api.py", line 216, in parse
    data = _open_resource(url_file_stream_or_string, etag, modified, agent, referrer, handlers, request_headers, result)
  File "C:\Users\rajdu\AppData\Roaming\Python\Python310\site-packages\feedparser\api.py", line 115, in _open_resource
    return http.get(url_file_stream_or_string, etag, modified, agent, referrer, handlers, request_headers, result)
  File "C:\Users\rajdu\AppData\Roaming\Python\Python310\site-packages\feedparser\http.py", line 171, in get
    f = opener.open(request)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Program Files\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Program Files\Python310\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Program Files\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Python310\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Program Files\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Program Files\Python310\lib\http\client.py", line 1447, in connect
    super().connect()
  File "C:\Program Files\Python310\lib\http\client.py", line 941, in connect
    self.sock = self._create_connection(
  File "C:\Program Files\Python310\lib\socket.py", line 833, in create_connection
    sock.connect(sa)
KeyboardInterrupt
^C

````
